In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [32]:
weather_data = pd.read_csv('weatherAUS.csv')

In [4]:
weather_data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [5]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null object
RISK_MM          142193 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(17), object(7)
memory usage: 26.0+ MB

In [6]:
weather_data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132923.000000,140845.000000,139563.000000,140419.000000,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,142193.000000
mean,12.186400,23.226784,2.349974,5.469824,7.624853,39.984292,14.001988,18.637576,68.843810,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,2.360682
std,6.403283,7.117618,8.465173,4.188537,3.781525,13.588801,8.893337,8.803345,19.051293,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,8.477969
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,0.000000
25%,7.600000,17.900000,0.000000,2.600000,4.900000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,0.000000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,0.000000
75%,16.800000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,0.800000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,371.000000

In [15]:
weather_data.isnull().sum().sort_values()

Date                 0
RISK_MM              0
RainTomorrow         0
Location             0
MaxTemp            322
MinTemp            637
Temp9am            904
WindSpeed9am      1348
Rainfall          1406
RainToday         1406
Humidity9am       1774
WindSpeed3pm      2630
Temp3pm           2726
Humidity3pm       3610
WindDir3pm        3778
WindGustSpeed     9270
WindGustDir       9330
WindDir9am       10013
Pressure3pm      13981
Pressure9am      14014
Cloud9am         53657
Cloud3pm         57094
Evaporation      60843
Sunshine         67816
dtype: int64

In [33]:
weather_data = weather_data.drop(['Sunshine', 'Evaporation', 'Cloud3pm', 'Cloud9am', 'Location', 'RISK_MM'], axis=1)

In [34]:
weather_data = weather_data.dropna()

In [26]:
weather_data.shape

(112925, 18)

In [27]:
from scipy import stats

In [35]:
z = np.abs(stats.zscore(weather_data._get_numeric_data()))
print(z)
weather_data = weather_data[(z < 3).all(axis=1)]
print(weather_data.shape)

[[0.11756741 0.10822071 0.20666127 ... 1.14245477 0.08843526 0.04787026]
 [0.84180219 0.20684494 0.27640495 ... 1.04184813 0.04122846 0.31776848]
 [0.03761995 0.29277194 0.27640495 ... 0.91249673 0.55672435 0.15688743]
 ...
 [1.44940294 0.23548728 0.27640495 ... 0.58223051 1.03257127 0.34701958]
 [1.16159206 0.46462594 0.27640495 ... 0.25166583 0.78080166 0.58102838]
 [0.77784422 0.4789471  0.27640495 ... 0.2085487  0.37167606 0.56640283]]
(107868, 18)

In [36]:
weather_data.head()

,Date,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,2008-12-02,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2008-12-03,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,2008-12-04,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,2008-12-05,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No

In [38]:
weather_data['RainToday'].replace({'Yes': 1, 'No':0}, inplace=True)

In [39]:
weather_data['RainTomorrow'].replace({'Yes': 1, 'No':0}, inplace=True)

In [40]:
categorical_columns = ['WindGustDir', 'WindDir3pm', 'WindDir9am']
for col in categorical_columns:
    print(np.unique(weather_data[col]))

['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']

In [41]:
weather_data = pd.get_dummies(weather_data, columns=categorical_columns)

In [42]:
weather_data

,Date,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,...,WindDir9am_NNW,WindDir9am_NW,WindDir9am_S,WindDir9am_SE,WindDir9am_SSE,WindDir9am_SSW,WindDir9am_SW,WindDir9am_W,WindDir9am_WNW,WindDir9am_WSW
0,2008-12-01,13.4,22.9,0.6,44.0,20.0,24.0,71.0,22.0,1007.7,...,0,0,0,0,0,0,0,1,0,0
1,2008-12-02,7.4,25.1,0.0,44.0,4.0,22.0,44.0,25.0,1010.6,...,1,0,0,0,0,0,0,0,0,0
2,2008-12-03,12.9,25.7,0.0,46.0,19.0,26.0,38.0,30.0,1007.6,...,0,0,0,0,0,0,0,1,0,0
3,2008-12-04,9.2,28.0,0.0,24.0,11.0,9.0,45.0,16.0,1017.6,...,0,0,0,1,0,0,0,0,0,0
4,2008-12-05,17.5,32.3,1.0,41.0,7.0,20.0,82.0,33.0,1010.8,...,0,0,0,0,0,0,0,0,0,0
5,2008-12-06,14.6,29.7,0.2,56.0,19.0,24.0,55.0,23.0,1009.2,...,0,0,0,0,0,0,0,1,0,0
6,2008-12-07,14.3,25.0,0.0,50.0,20.0,24.0,49.0,19.0,1009.6,...,0,0,0,0,0,0,1,0,0,0
7,2008-12-08,7.7,26.7,0.0,35.0,6.0,17.0,48.0,19.0,1013.4,...,0,0,0,0,1,0,0,0,0,0
8,2008-12-09,9.7,31.9,0.0,80.0,7.0,28.0,42.0,9.0,1008.9,...,0,0,0,1,0,0,0,0,0,0
9,2008-12-10,13.1,30.1,1.4,28.0,15.0,11.0,58.0,27.0,1007.0,...,0,0,1,0,0,0,0,0,0,0
10,2008-12-11,13.4,30.4,0.0,30.0,17.0,6.0,48.0,22.0,1011.8,...,0,0,0,0,1,0,0,0,0,0
11,2008-12-12,15.9,21.7,2.2,31.0,15.0,13.0,89.0,91.0,1010.5,...,0,0,0,0,0,0,0,0,0,0
13,2008-12-14,12.6,21.0,3.6,44.0,24.0,20.0,65.0,43.0,1001.2,...,0,0,0,0,0,0,0,1,0,0
15,2008-12-17,14.1,20.9,0.0,22.0,11.0,9.0,69.0,82.0,1012.2,...,0,0,0,0,0,1,0,0,0,0
16,2008-12-18,13.5,22.9,16.8,63.0,6.0,20.0,80.0,65.0,1005.8,...,0,0,0,0,0,0,0,0,0,0
17,2008-12-19,11.2,22.5,10.6,43.0,24.0,17.0,47.0,32.0,1009.4,...,0,0,0,0,0,0,0,0,0,1
18,2008-12-20,9.8,25.6,0.0,26.0,17.0,6.0,45.0,26.0,1019.2,...,0,0,0,1,0,0,0,0,0,0
19,2008-12-21,11.5,29.3,0.0,24.0,9.0,9.0,56.0,28.0,1019.3,...,0,0,0,1,0,0,0,0,0,0
20,2008-12-22,17.1,33.0,0.0,43.0,17.0,22.0,38.0,28.0,1013.6,...,0,0,0,0,0,0,0,0,0,0
21,2008-12-23,20.5,31.8,0.0,41.0,19.0,20.0,54.0,24.0,1007.8,...,0,0,0,0,0,0,0,1,0,0
22,2008-12-24,15.3,30.9,0.0,33.0,6.0,13.0,55.0,23.0,1011.0,...,0,0,0,0,0,0,0,0,0,0
23,2008-12-25,12.6,32.4,0.0,43.0,4.0,19.0,49.0,17.0,1012.9,...,0,0,0,0,0,0,0,0,0,0
24,2008-12-26,16.2,33.9,0.0,35.0,9.0,13.0,45.0,19.0,1010.9,...,0,0,0,1,0,0,0,0,0,0
26,2008-12-28,20.1,32.7,0.0,48.0,13.0,30.0,56.0,15.0,1005.2,...,0,0,0,0,0,0,0,0,0,0
27,2008-12-29,19.7,27.2,0.0,46.0,19.0,30.0,49.0,22.0,1004.8,...,0,1,0,0,0,0,0,0,0,0
28,2008-12-30,12.5,24.2,1.2,50.0,11.0,22.0,78.0,70.0,1005.6,...,0,0,0,0,0,0,0,0,0,1
29,2008-12-31,12.0,24.4,0.8,39.0,17.0,17.0,48.0,28.0,1006.1,...,0,0,0,0,0,0,0,0,1,0
30,2009-01-01,11.3,26.5,0.0,56.0,19.0,31.0,46.0,26.0,1004.5,...,0,0,0,0,0,0,0,1,0,0
31,2009-01-02,9.6,23.9,0.0,41.0,19.0,11.0,44.0,22.0,1014.4,...,0,0,0,0,0,0,0,0,0,1
32,2009-01-03,10.5,28.8,0.0,26.0,11.0,7.0,43.0,22.0,1018.7,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142162,2017-05-25,14.6,26.3,0.0,37.0,19.0,20.0,61.0,36.0,1022.0,...,0,0,0,0,0,1,0,0,0,0
142164,2017-05-27,9.3,28.0,0.0,28.0,6.0,11.0,36.0,16.0,1019.9,...,0,0,0,0,0,1,0,0,0,0
142165,2017-05-28,8.0,24.6,0.0,33.0,11.0,13.0,46.0,25.0,1021.7,...,0,0,0,1,0,0,0,0,0,0
142166,2017-05-29,12.7,22.2,0.0,37.0,19.0,13.0,59.0,34.0,1024.3,...,0,0,0,0,0,0,0,0,0,0
142167,2017-05-30,9.4,22.7,0.0,35.0,13.0,17.0,62.0,32.0,1026.6,...,0,0,0,1,0,0,0,0,0,0
142168,2017-05-31,5.4,20.5,0.0,46.0,20.0,28.0,56.0,32.0,1029.2,...,0,0,0,0,0,0,0,0,0,0
142169,2017-06-01,5.6,19.4,0.0,43.0,22.0,24.0,61.0,22.0,1029.6,...,0,0,0,0,0,0,0,0,0,0
142170,2017-06-02,1.5,19.2,0.0,37.0,17.0,22.0,45.0,18.0,1030.7,...,0,0,0,0,0,0,0,0,0,0
142171,2017-06-03,3.8,19.8,0.0,39.0,19.0,17.0,42.0,22.0,1028.7,...,0,0,0,0,0,0,0,0,0,0
142172,2017-06-04,4.5,18.8,0.0,31.0,13.0,15.0,42.0,26.0,1026.9,...,0,0,0,0,0,0,0,0,0,0
142173,2017-06-05,4.9,20.7,0.0,37.0,17.0,24.0,38.0,11.0,1027.1,...,0,0,0,0,0,0,0,0,0,0
142174,2017-06-06,1.2,20.8,0.0,43.0,13.0,28.0,29.0,6.0,1029.8,...,0,0,0,0,0,0,0,0,0,0
142175,2017-06-07,0.5,21.7,0.0,43.0,13.0,20.0,27.0,19.0,1029.0,...,0,0,0,0,0,0,0,0,0,0
142176,2017-06-08,4.0,20.0,0.0,39.0,13.0,26.0,58.0,26.0,1030.2,...,0,0,0,0,0,0,0,0,0,0
142177,2017-06-09,3.4,19.8,0.0,43.0,19.0,24.0,54.0,23.0,1031.8,...,0,0,0,0,0,0,0,0,0,0
142178,2017-06-10,3.2,18.6,0.0,46.0,15.0,20.0,56.0,29.0,1031.0,...,0,0,0,0,0,0,0,0,0,0
142179,2017-06-11,2.4,19.1,0.0,33.0,17.0,17.0,59.0,24.0,1030.0,...,0,0,0,1,0,0,0,0,0,0
142180,2017-06-12,5.1,19.7,0.0,46.0,13.0,17.0,56.0,29.0,1028.5,...,0,0,0,0,0,0,0,0,0,0
142181,2017-06-13,2.5,21.2,0.0,35.0,17.0,19.0,57.0,32.0,1027.2,...,0,0,0,0,0,0,0,0,0,0
142182,2017-06-14,2.3,21.4,0.0,22.0,11.0,7.0,60.0,28.0,1026.9,...,0,0,0,1,0,0,0,0,0,0
142183,2017-06-15,2.6,22.5,0.0,19.0,9.0,7.0,59.0,24.0,1025.0,...,0,0,1,0,0,0,0,0,0,0
142184,2017-06-16,5.2,24.3,0.0,24.0,11.0,11.0,53.0,24.0,1023.8,...,0,0,0,1,0,0,0,0,0,0
142185,2017-06-17,6.4,23.4,0.0,31.0,15.0,17.0,53.0,25.0,1025.8,...,0,0,1,0,0,0,0,0,0,0
142186,2017-06-18,8.0,20.7,0.0,41.0,19.0,26.0,56.0,32.0,1028.1,...,0,0,0,1,0,0,0,0,0,0
142187,2017-06-19,7.4,20.6,0.0,35.0,15.0,17.0,63.0,33.0,1027.2,...,0,0,0,0,0,0,0,0,0,0
142188,2017-06-20,3.5,21.8,0.0,31.0,15.0,13.0,59.0,27.0,1024.7,...,0,0,0,0,0,0,0,0,0,0
142189,2017-06-21,2.8,23.4,0.0,31.0,13.0,11.0,51.0,24.0,1024.6,...,0,0,0,1,0,0,0,0,0,0
142190,2017-06-22,3.6,25.3,0.0,22.0,13.0,9.0,56.0,21.0,1023.5,...,0,0,0,1,0,0,0,0,0,0
142191,2017-06-23,5.4,26.9,0.0,37.0,9.0,9.0,53.0,24.0,1021.0,...,0,0,0,1,0,0,0,0,0,0
142192,2017-06-24,7.8,27.0,0.0,28.0,13.0,7.0,51.0,24.0,1019.4,...,0,0,0,0,1,0,0,0,0,0

In [44]:
from sklearn.preprocessing import MinMaxScaler

In [48]:
scaler = MinMaxScaler()

In [49]:
weather_data = weather_data.drop('Date', axis=1)

In [50]:
scaler.fit(weather_data)

/Users/charlie/anaconda3/envs/py36/lib/python2.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [51]:
weather_data = pd.DataFrame(scaler.transform(weather_data), index=weather_data.index, columns=weather_data.columns)

In [52]:
from sklearn.feature_selection import SelectKBest, chi2

In [55]:
X = weather_data.loc[:, weather_data.columns != 'RainTomorrow']

In [56]:
y = weather_data[['RainTomorrow']]

In [57]:
selector = SelectKBest(chi2, k=3)

In [58]:
selector.fit(X, y)

SelectKBest(k=3, score_func=<function chi2 at 0x1a119c8938>)

In [59]:
X_new = selector.transform(X)

In [60]:
print(X.columns[selector.get_support(indices=True)])

Index([u'Rainfall', u'Humidity3pm', u'RainToday'], dtype='object')

In [61]:
df = weather_data[['Humidity3pm','Rainfall','RainToday','RainTomorrow']]
X = df[['Humidity3pm', 'Rainfall', 'RainToday']]
y = df[['RainTomorrow']]

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [79]:
import time

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [74]:
logmodel = LogisticRegression()

In [75]:
logmodel.fit(X_train, y_train)

/Users/charlie/anaconda3/envs/py36/lib/python2.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [76]:
predictions = logmodel.predict(X_test)

In [77]:
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.838138500046352
[[24584  1008]
 [ 4230  2539]]
              precision    recall  f1-score   support

         0.0       0.85      0.96      0.90     25592
         1.0       0.72      0.38      0.49      6769

   micro avg       0.84      0.84      0.84     32361
   macro avg       0.78      0.67      0.70     32361
weighted avg       0.82      0.84      0.82     32361

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [119]:
rfc = RandomForestClassifier(n_estimators=200, max_depth=4)

In [120]:
rfc.fit(X_train, y_train)

/Users/charlie/anaconda3/envs/py36/lib/python2.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=4, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [121]:
rfc_pred = rfc.predict(X_test)

In [122]:
t0 = time.time()
print(accuracy_score(y_test, rfc_pred))
print(confusion_matrix(y_test, rfc_pred))
print(classification_report(y_test, rfc_pred))
print("Time taken: ", time.time()-t0)

0.8388183307067149
[[24650   942]
 [ 4274  2495]]
              precision    recall  f1-score   support

         0.0       0.85      0.96      0.90     25592
         1.0       0.73      0.37      0.49      6769

   micro avg       0.84      0.84      0.84     32361
   macro avg       0.79      0.67      0.70     32361
weighted avg       0.83      0.84      0.82     32361

('Time taken: ', 0.067169189453125)

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
dtc = DecisionTreeClassifier()

In [91]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [123]:
dtc_pred = dtc.predict(X_test)

In [124]:
t0 = time.time()
print(accuracy_score(y_test, dtc_pred))
print(confusion_matrix(y_test, dtc_pred))
print(classification_report(y_test, dtc_pred))
print("Time taken: ", time.time()-t0)

0.828002842928216
[[24511  1081]
 [ 4485  2284]]
              precision    recall  f1-score   support

         0.0       0.85      0.96      0.90     25592
         1.0       0.68      0.34      0.45      6769

   micro avg       0.83      0.83      0.83     32361
   macro avg       0.76      0.65      0.67     32361
weighted avg       0.81      0.83      0.80     32361

('Time taken: ', 0.07664608955383301)

In [125]:
from sklearn.svm import SVC

In [126]:
svm = SVC()

In [132]:
svm.fit(X_train, y_train)

/Users/charlie/anaconda3/envs/py36/lib/python2.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [133]:
svm_pred = svm.predict(X_test)

In [134]:
t0 = time.time()
print(accuracy_score(y_test, svm_pred))
print(confusion_matrix(y_test, svm_pred))
print(classification_report(y_test, svm_pred))
print("Time taken: ", time.time()-t0)

0.8233985352739408
[[24999   593]
 [ 5122  1647]]
              precision    recall  f1-score   support

         0.0       0.83      0.98      0.90     25592
         1.0       0.74      0.24      0.37      6769

   micro avg       0.82      0.82      0.82     32361
   macro avg       0.78      0.61      0.63     32361
weighted avg       0.81      0.82      0.79     32361

('Time taken: ', 0.06340289115905762)